pipeline {
    agent { label 'agent-1'}
    options {
        disableConcurrentBuilds()
    }
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'select one')
    }
    stages {
        stage ('triggering') {
            steps {
                script {
                    sh """
                    echo "second echo"
                    """
                }
            }
        }
       stage('triggering-echo-3') {
        when {
            expression {params.ACTION == 'apply'}
        }
        steps {
            build job: 'echo-3', parameters: [string(name: 'ACTION', choices: ['apply', 'destroy'])], propagate: true
        }
       }
    }
}