pipeline {
    agent { label 'agent-1'}
    options {
        disableConcurrentBuilds()
    }
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'select one')
    }
    stages {
        stage ('triggering') {
            steps {
                input message: 'Do you want to deploy', ok: 'Yes please'
                script {
                    sh """
                    echo "first echo"
                    """
                }
            }
        }
        stage(trigger-echo-2) {
            when {
                expression { params.ACTION == 'apply' }
            }
            steps {
                build job: 'echo-2', parameters: [string(name: 'ACTION', value: 'apply')], propagate: true
            }
        }
    
    }
    post {
        success {
            echo "success"
        }
        failure {
            echo "failure"
        }
    }
}