pipeline {
    agent { label 'agent-1'}
    options {
        disableConcurrentBuilds()
    }
    stages {
        stage (triggering) {
            steps {
                script {
                    sh """
                    echo "first echo"
                    """
                }
            }
        }
    }
}